const data = {
  products: [
    {
      id: '1',
      name: 'Slim Shirt',
      category: 'Shirts',
      image: '/images/d1.jpg',
      price: 60,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
    },
    {
      id: '2',
      name: 'Slim Shirt',
      category: 'Shirts',
      image: '/images/d1.jpg',
      price: 60,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 6,
    },
    {
      id: '3',
      name: 'Slim Pants',
      category: 'Pants',
      image: '/images/d1.jpg',
      price: 60,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
    },
    {
      id: '4',
      name: 'Slim Pants',
      category: 'Pants',
      image: '/images/d1.jpg',
      price: 60,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
    },
    {
      id: '5',
      name: 'Slim Pants',
      category: 'Pants',
      image: '/images/d1.jpg',
      price: 60,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
    },
    {
      id: '6',
      name: 'Slim Pants',
      category: 'Pants',
      image: '/images/d1.jpg',
      price: 60,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
    },
  ],
};

export default data;
